---
title: "3_test_apply_lm_corrections"
output: html_document
---


TO DO:


```{r}
ll = '/projects/tropics/users/cquinn/R_400/'
.libPaths(c( .libPaths(), ll))
library(dplyr)
library(tidyr)
library(ggplot2)

source('/projects/tropics/users/cquinn/s2l/code/paper1-AcousticIndices/utility_fxs.R')
```

```{r}
wd = '/projects/tropics/users/cquinn/s2l/paper1-AcousticIndices/'
model_list = readRDS(paste0(wd, 'results/paired_ARUs/corrected_data/lm_paired_ARU_models-no_outlier_rm.rds'))
```

0. Bring in paired ARU csv
```{r}
# read in paired ARU csv with AM site list and LG site list
paired_df = read.csv(paste0(wd,'results/paired_ARUs/colocated_ARUs-paired.csv')) %>%
  dplyr::select(SiteID, Number.of.Recordings, Paired_site) %>%
  filter(grepl('am', SiteID)) # 24 paired sites (48 ARUs)

# Read in paired csvs
pair_preds = abgqi_pair_reader(paired_df) %>%
  filter(!(SiteID == 3 | SiteID == 5))
pair_indices = acoustic_index_pair_reader(paired_df) %>%
  filter(!(SiteID == 3 | SiteID == 5))
```

```{r}
# Derive average hourly and site values
# ABGQI
pair_preds$DDHH = substr(pair_preds$DDHHmm,1,4)
by_hr_abgqi = pair_preds %>%
  select(-wav, -DDHHmm, -melspec) %>%
  group_by(SiteID, site_AM, site_LG, soundType, DDHH) %>%
  summarise(across(everything(), mean)) 

by_site_abgqi = pair_preds %>%
  select(-wav, -DDHHmm, -melspec, -DDHH) %>%
  group_by(SiteID, site_AM, site_LG, soundType) %>%
  summarise(across(everything(), mean)) 


# Acoustic indices
pair_indices$DDHH = substr(pair_indices$DDHHmm,1,4)
by_hr_indices = pair_indices %>%
  select(-wav, -DDHHmm) %>%
  group_by(SiteID, site_AM, site_LG, acIndex, DDHH) %>%
  summarise(across(everything(), mean))

by_site_indices = pair_indices %>%
  select(-wav, -DDHHmm, -DDHH) %>%
  group_by(SiteID, site_AM, site_LG, acIndex) %>%
  summarise(across(everything(), mean))
```


1. Check whether corrected LG data results in non-significant Wilcoxon tests
ANTHROPHONY
```{r}
# check our model for transformations
model_list$Anthro

# create new transformed data to predict on
corrected_df = by_hr_abgqi %>%
  ungroup() %>%
  filter(soundType == 'Anthrophony') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$Anthro, newdata = corrected_df)

# transform response (logAM) back to standard scale (0-1)
corrected_df = corrected_df %>%
  mutate(LG_corr = exp(y_pred)) %>%
  mutate(LG_corr = ifelse(LG_corr > 1, 1, LG_corr))

# HOURLY
# V = 783997, p-value = 2.467e-10
# V = 800529, p-value = 6.036e-13 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))


# SITE
# V = 163, p-value = 0.2479
# V = 171, p-value = 0.156 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG_corr) %>%
  rename(LG = LG_corr) %>%
  index_boxplot()
```

BIOPHONY
```{r}
# check our model for transformations
model_list$Biophony

# create new transformed data to predict on
corrected_df = by_hr_abgqi %>%
  ungroup() %>%
  filter(soundType == 'Biophony') %>% 
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$Biophony, newdata = corrected_df)

# transform back to response scale (0-1)
corrected_df = corrected_df %>%
  mutate(LG_corr = y_pred^2)

# V = 780704, p-value = 7.479e-10
# V = 797781, p-value = 1.727e-12 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 179, p-value = 0.09173
# V = 183, p-value = 0.06844 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG_corr) %>%
  rename(LG = LG_corr) %>%
  index_boxplot()
```

QUIET
```{r}
# check our model for transformations
model_list$Quiet
summary(model_list$Quiet)

# create new transformed data to predict on
corrected_df = by_hr_abgqi %>%
  ungroup() %>%
  filter(soundType == 'Quiet') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$Quiet, newdata = corrected_df)

# Quiet AM was not transformed, prediction is on standard scale
corrected_df = corrected_df %>%
  mutate(LG_corr = y_pred)

# V = 674611, p-value = 0.5698
# V = 679326, p-value = 0.4141 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

corrected_df %>%
  select(AM, LG_corr) %>%
  rename(LG = LG_corr) %>%
  index_boxplot()

# SITE
# V = 129, p-value = 0.9493
# V = 129, p-value = 0.9493 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
      geom_jitter(width = 0.1, alpha = 0.3) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE) +
      labs(title = "Paired ARU corrections by-site for Quiet") +
      ylab('Percent present') +
      xlab('ARU model')
  
```

INTERFERENCE
```{r}
# check our model for transformations
model_list$Interference

# create new transformed data to predict on
corrected_df = by_hr_abgqi %>%
  ungroup() %>%
  filter(soundType == 'Interference') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$Interference, newdata = corrected_df)

# transform response (logAM) back to standard scale (0-1)
corrected_df = corrected_df %>%
  mutate(LG_corr = exp(y_pred)) %>%
  mutate(LG_corr = ifelse(LG_corr > 1, 1, LG_corr))

# V = 783533, p-value = 2.889e-10
# V = 779521, p-value = 1.106e-09 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 183, p-value = 0.06844
# V = 184, p-value = 0.06342 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

ACI
```{r}
# check our model for transformations
model_list$ACI

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'ACI') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$ACI, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = exp(y_pred))

# V = 480204, p-value < 2.2e-16
# V = 449209, p-value < 2.2e-16 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 88, p-value = 0.2221
# V = 82, p-value = 0.156 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

ADI
```{r}
# check our model for transformations
model_list$ADI

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'ADI') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$ADI, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = (y_pred)^(1/3))

# V = 692525, p-value = 0.1306
# V = 708970, p-value = 0.01741 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 88, p-value = 0.2221
# V = 94, p-value = 0.3053 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

AEI
```{r}
# check our model for transformations
model_list$AEI

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'AEI') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$AEI, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = (y_pred)^2)

# V = 732483, p-value = 0.000299
# V = 750498, p-value = 4.998e-06 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 172, p-value = 0.1465
# V = 178, p-value = 0.09841 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

BI
```{r}
# check our model for transformations
model_list$BI

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'BI') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$BI, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = exp(y_pred))

# V = 750032, p-value = 5.617e-06
# V = 749104, p-value = 7.074e-06 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 168, p-value = 0.187
# V = 171, p-value = 0.156 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```


H
```{r}
# check our model for transformations
model_list$H

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'H') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$H, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = fromLogit(y_pred))

# V = 639846, p-value = 0.2068
# V = 625082, p-value = 0.04136 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 116, p-value = 0.7502
# V = 109, p-value = 0.5879 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

Hs
```{r}
# check our model for transformations
model_list$Hs

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'Hs') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$Hs, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = fromLogit(y_pred))

# V = 637571, p-value = 0.1669
# V = 622582, p-value = 0.02989 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 99, p-value = 0.388
# V = 91, p-value = 0.2615 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

Ht
```{r}
# check our model for transformations
model_list$Ht

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'Ht') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$Ht, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = fromLogit(y_pred))

# V = 679121, p-value = 0.4203
# V = 675406, p-value = 0.5417 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 108, p-value = 0.5661
# V = 106, p-value = 0.5235 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```
M
```{r}
# check our model for transformations
model_list$M

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'M') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$M, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = exp(y_pred))

# V = 574946, p-value = 2.865e-06
# V = 586621, p-value = 4.795e-05 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 105, p-value = 0.5028
# V = 120, p-value = 0.8486 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

R
```{r}
# check our model for transformations
model_list$R

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'R') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$R, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = exp(y_pred))

# V = 766912, p-value = 5.658e-08
# V = 766912, p-value = 5.658e-08 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 167, p-value = 0.1982
# V = 167, p-value = 0.1982 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

rugo
```{r}
# check our model for transformations
model_list$rugo

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'rugo') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$rugo, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = exp(y_pred))

# V = 808950, p-value = 2.12e-14
# V = 794199, p-value = 6.588e-12 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 191, p-value = 0.03588
# V = 186, p-value = 0.05425 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

sfm
```{r}
# check our model for transformations
model_list$sfm

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'sfm') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$sfm, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = (y_pred))

# V = 687350, p-value = 0.2152
# V = 630032, p-value = 0.0752 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 127, p-value = 1
# V = 116, p-value = 0.7502 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

zcr_mean
```{r}
# check our model for transformations
model_list$zcr_mean

# create new transformed data to predict on
corrected_df = by_hr_indices %>%
  ungroup() %>%
  filter(acIndex == 'zcr_mean') %>%
  select(SiteID, AM, LG)

# prediction
corrected_df$y_pred = predict(model_list$zcr_mean, newdata = corrected_df)

# transform response (logAM)
corrected_df = corrected_df %>%
  mutate(LG_corr = (y_pred))

# V = 658972, p-value = 0.7986
# V = 662048, p-value = 0.9258 (Outliers included)
(mod = wilcox.test(corrected_df$AM, corrected_df$LG_corr, paired = TRUE))

# SITE
# V = 136, p-value = 0.7745
# V = 139, p-value = 0.7024 (Outliers included)
corrected_df_site = corrected_df%>%
  group_by(SiteID) %>%
  summarise(across(everything(), mean))
(mod = wilcox.test(corrected_df_site$AM, corrected_df_site$LG_corr, paired = TRUE))

corrected_df_site %>%
  select(AM, LG, LG_corr) %>%
  gather(variable, value) %>%
  ggplot(aes(x = variable, y = value)) +
  geom_jitter(width = 0.1, alpha = 0.1) + 
      geom_boxplot(alpha = 0.4, outlier.shape = NA, notch = TRUE)
  
```

